#include <algorithm>
#include <iomanip>
#include <iostream>
#include <string_view>
#include "Strings.hpp"

using namespace std;

namespace
{
    const char* TextName(i18n::TextId id)
    {
        switch (id)
        {
            // NOTE: Auto-generated by CMake
#include "I18NTextNames.inc"
        default:
            return "<unknown>";
        }
    }
} // namespace

int main(int argc, char** argv)
{
    optional<AppLocale> selectedLocale;
    if (argc != 1)
    {
        if (argc != 3 || string_view(argv[1]) != "--locale")
        {
            cerr << "Usage: tooling_I18NCheck [--locale " << i18n::kLocaleOptionString << " ]\n";
            return 2;
        }
        selectedLocale = i18n::ParseLocale(argv[2]);
        if (!selectedLocale)
        {
            cerr << "Invalid locale: " << argv[2] << ". Expected " << i18n::kLocaleOptionString << endl;
            return 2;
        }
    }

    i18n::StringTable const& defaults = *i18n::GetStringTable(AppLocale::DEFAULT);
    size_t stringCount = static_cast<size_t>(i18n::TextId::Count);
    size_t localeCount = static_cast<size_t>(AppLocale::NUM_LOCALES);

    size_t total = 0;
    for (size_t localeIndex = 0; localeIndex < localeCount; ++localeIndex)
    {
        const AppLocale locale = static_cast<AppLocale>(localeIndex);
        if (selectedLocale ? locale != *selectedLocale : locale == AppLocale::DEFAULT)
            continue;
        i18n::StringTable const& strings = *i18n::GetStringTable(locale);
        auto missing = [&](size_t i) { return defaults[i] != nullptr && (!strings[i] || !*strings[i]); };

        size_t missed = 0;
        for (size_t i = 0; i < stringCount; i++)
            missed += missing(i);
        
        cout << format_as(locale) << " has " << missed << " missing translation(s):\n\n";
        for (size_t i = 0, miss = 0; i < stringCount; i++)
        {
            if (!missing(i))
                continue;
            miss++;
            cout << TextName(static_cast<i18n::TextId>(i));
            if (miss != missed)
                cout << ",";
        }        
        cout << "\n\n";
        total += missed;
    }
    cout << "Total missing translation(s): " << total << '\n';
    return total != 0 ? 1 : 0;
}
